name: jecomprendrien

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-version: 4.14.x
    
      - run: opam install . --deps-only --with-doc --with-test
      - run: opam install yocaml
      - run: opam install yocaml_unix yocaml_yaml yocaml_jingoo
      - run: opam exec -- dune exec bin/main.exe -- build
    
    
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          publish_branch: gh-pages
