name: jecomprend

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14.x
    
      - run: opam install . --deps-only --with-doc --with-test
      - run: opam install yocaml
      - run: opam install yocaml_unix yocaml_markdown yocaml_yaml yocaml_mustache
      - run: opam exec -- dune exec bin/main.exe -- build
    
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site/oxywa
          publish_branch: gh-pages
          enable_jekyll: false
